"""Reproduce M4-12 static content, with original execution only before the race.

The 1512-byte landing coefficient matrices are generated by $81:9A4D–9E12
before the first race update. Extraction stops at frame 1297, before frame 1377.
"""
from __future__ import annotations
import argparse
import json
import tempfile
from pathlib import Path
from .zoom_zoo_trial import content_inventory, check_content
from .zoom_zoo_trial_reference import ROOT, ROM_SHA, PRIMARY_SHA, sha
from .zoom_zoo_contact import extract_content
from ..reference.bsnes import BsnesCore
from ..reference.worker import inputs_for_frame
from ..replay.manifest import derive_script
from ..reference.core_identity import accepted_reference, require_core

def extract(out,library):
    if out.exists() and any(out.iterdir()):raise ValueError('refusing to overwrite nonempty extraction')
    rom_path=Path((ROOT/'local/rom-location.txt').read_text().strip());rom=rom_path.read_bytes()
    manifest=(ROOT/'tests/manifests/replay/race-crawler-zoom-zoo-3300.json').read_bytes()
    core_sha=require_core(library)
    if sha(rom)!=ROM_SHA or sha(manifest)!=PRIMARY_SHA:raise ValueError('extraction identity differs')
    extract_content(ROOT/'tests/manifests/content/zoom-zoo-reference-contract.json',rom_path,out)
    inventory=content_inventory()
    entries=json.loads((ROOT/'tests/manifests/content/classic-crawler-dragster-pack.json').read_text())['entries']
    for name,identity in inventory.items():
        if (out/name).exists():continue
        match=[e for e in entries if e['sha256']==identity['sha256'] and e['source']['kind']=='raw']
        if match:
            data=b''.join(rom[p['file_offset']:p['file_offset']+p['length']] for p in match[0]['source']['pieces'])
            (out/name).write_bytes(data)
    (out/'reflection-pose-table.bin').write_bytes(rom[0x122db:0x1235b])
    (out/'reflected-vertical-slope-coefficients.bin').write_bytes(rom[0x22b:0x234]+rom[0x24b:0x254])
    (out/'vertical-slope-coefficients.bin').write_bytes(rom[0x22b:0x231]+rom[0x24b:0x251])
    script=derive_script(json.loads(manifest))
    with tempfile.TemporaryDirectory(prefix='zz-static-',dir=out.parent) as directory:
        core=BsnesCore(library,Path(directory),script.get('core_options'))
        try:
            core.load(rom_path);core.set_serialization_method('Strict')
            for frame in range(1298):
                for port,buttons in inputs_for_frame(script,frame).items():core.set_inputs(port,buttons)
                core.run_frame()
            data=core.wram()[0x572:0xb5a]
        finally:core.unload()
    (out/'landing-response-matrices.bin').write_bytes(data)
    check_content(out)
    report={'kind':'m4_12_static_extraction','rom_sha256':ROM_SHA,'core_sha256':core_sha,'original_last_frame':1297,'first_race_update':1377,'items':inventory}
    (out/'trial-content.json').write_text(json.dumps(report,indent=2)+'\n');return report

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--core',type=Path,required=True);parser.add_argument('--out',type=Path,required=True);a=parser.parse_args()
    try:extract(a.out,a.core);print('M4-12 static content reproduced and authenticated')
    except (ValueError,OSError) as e:parser.exit(1,f'{e}\n')
if __name__=='__main__':main()
